name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Print the value of MY_VARIABLE
      run: MY_VARIABLE='Hello, GitHub Actions!' && echo $MY_VARIABLE
        
      env:
        DAY_OF_WEEK: Monday
      
  greeting_job:
    runs-on: ubuntu-latest
    env:
        Greeting: Hello
    steps:
    - name: "Say Hello Mona it's Monday"
      run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      env:
        First_Name: Mona
      